name: okcash
version: master
summary: A Decentralized, Sustainable Staking Cryptocurrency Platform
description: |
Okcash presents a pioneering peer-to-peer platform, crafted under an open-source framework, encapsulating a native cryptocurrency alongside a Long-Term Sustainable Staking (LTSS) model. 
This decentralized ecosystem is engineered to deliver a rapid, dependable, and eco-friendly Proof of Stake mechanism accessible to all. 
Okcash is designed with a focus on user-friendliness, ensuring ease of use for everyone, from tech enthusiasts to those less familiar with digital currencies. 
Through Okcash, users engage in a secure, efficient staking process, contributing to a robust, decentralized network while earning rewards, making it a standout in the realm of digital finance.

grade: devel
confinement: strict

apps:
  okcash:
    command: desktop-launch $SNAP/usr/local/bin/okcash
    plugs: [network, network-bind, unity7]

parts:
  okcash:
    source: .
    plugin: qmake
    qt-version: qt5
    build-packages:
      - build-essential
      - qt5-default
      - qtbase5-dev-tools
      - qttools5-dev-tools
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-program-options-dev
      - libboost-system-dev
      - libboost-thread-dev
      - libdb++-dev
      - libminiupnpc-dev
      - libqt5webkit5-dev
      - libssl-dev
    after: [desktop-qt5]
