#!/bin/bash
set -e

OTOOL=${HOST}-otool INSTALLNAMETOOL=${HOST}-install_name_tool STRIP=${HOST}-strip contrib/macdeploy/macdeployqtplus Okcash.app
mkdir -p dist/.background
install contrib/macdeploy/background.png dist/.background
install contrib/macdeploy/DS_Store dist/.DS_Store
install src/qt/res/icons/okcash.icns dist/.VolumeIcon.icns
cd dist
ln -sf /Applications Applications
cd ..
genisoimage -no-cache-inodes -l -probe -V "Okcash" -no-pad -r -apple -o okcash.tmp.dmg dist
dmg dmg okcash.tmp.dmg okcash.macosx.dmg
