export default [
  { "fact": "Ruby starts recording a message for Harvard about her college admissions essay, discussing her uniqueness and qualifications.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "Ruby is recording this to help with her writer's block as advised by Ms. Gund." },
  { "fact": "Ruby discusses her experience of traveling through the multiverse via a portal hidden inside a tree trunk.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "The portal was built in the mid-1800s by an inventor named Padraig O’Direáin." },
  { "fact": "Ruby mentions encountering various versions of her life in parallel universes during her travels.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "This experience is central to what makes her unique for her college essay." },
  { "fact": "Ruby describes the scientific basis for the multiverse theory she's experienced, referencing prominent scientists and theories.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "She points to the work of Hugh Everett, Brian Greene, Michio Kaku, and Lisa Randall to explain her experiences." },
  { "fact": "Ruby's return from the multiverse is fraught with danger, including lightning and fire.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "Her father, Alan Wright, finds her after she reappears, expressing relief and concern." },
  { "fact": "Ruby struggles with emotional turmoil following her multiverse travels, leading to a strained relationship with her father.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "Her father suggests she may have been hallucinating due to a possible brain injury from lightning." },
  { "fact": "Ruby becomes obsessed with understanding and proving the reality of her multiverse travels, developing technology and theories.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "She builds models of the portal device, one of which works." },
  { "fact": "Ruby discusses the strain her obsession has put on her life and relationships, particularly with her father.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 0, "additionalContext": "Her father suggests she try something new to possibly find happiness outside her scientific pursuits." },
  { "fact": "Ruby successfully activates her portal device, jumping to an alternate universe.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 27, "additionalContext": "She describes the physical and environmental differences in this new universe, noting pollution and decay." },
  { "fact": "Ruby encounters an alternate version of herself in the polluted universe, who appears to be on a mission to eliminate 'shitty universes.'", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 27, "additionalContext": "The alternate Ruby is causing deliberate damage to the fabric of spacetime." },
  { "fact": "The alternate Ruby reveals that she has been jumping between universes for 27 days, causing destabilization.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 27, "additionalContext": "She believes her actions are justified by eliminating universes she deems unworthy." },
  { "fact": "Ruby realizes the threat her alternate self poses to the multiverse and decides to stop her, despite the dangers.", "estimatedTimeOfDay": "unknown", "estimatedDaysFromStart": 27, "additionalContext": "She understands the significance of her actions and the potential consequences of not intervening." }
]
